Description: >
    Ayomide Johnson Salami / Software Engineer
    This template creates a role that gives permission to access an s3 bucket

Parameters:
    EnvironmentName:
        Description: Environment name that will be prefixed to resource names
        Type: String

Resources:
    AyomideS3ReadOnlyRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: S3ReadOnly
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - "ec2.amazonaws.com"
                      Action:
                          - sts:AssumeRole
            Path: "/"


    AyomideS3ReadOnlyPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: S3ReadOnlyAccess
            PolicyDocument:
                Statement:
                    - Effect: Allow
                      Action:
                          - s3:Get*
                          - s3:List*
                      Resource:
                          - arn:aws:s3:::udacity-demo-1
                          - arn:aws:s3:::udacity-demo-1/*
            Roles:
                - Ref: AyomideS3ReadOnlyRole 

    ProfileInstance:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: "/"
            Roles:
                - Ref: AyomideS3ReadOnlyRole

Outputs:
    ProfileInstance:
        Description: A role for EC2
        Value: !GetAtt ProfileInstance.Arn
        Export:
            Name: ayomideProfileInstance
