Description: >
    Ayomide Johnson Salami / Software Engineer
    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets. It also deploys Compute resources
    EC2 within an Auto Scaling Group and a Loadbalancer.

Parameters:
    EnvironmentName:
        Description: Environment name that will be prefixed to resource names
        Type: String

Resources:
    AyomideS3ReadOnlyRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: S3ReadOnly
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - "ec2.amazonaws.com"
                      Action:
                          - sts:AssumeRole
            Path: "/"


    AyomideS3ReadOnlyPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: S3ReadOnlyAccess
            PolicyDocument:
                Statement:
                    - Effect: Allow
                      Action:
                          - s3:Get*
                          - s3:List*
                      Resource:
                          - arn:aws:s3:::udacity-demo-1
                          - arn:aws:s3:::udacity-demo-1/*
            Roles:
                - Ref: AyomideS3ReadOnlyRole 

    ProfileInstance:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: "/"
            Roles:
                - Ref: AyomideS3ReadOnlyRole

Outputs:
    ProfileInstance:
        Description: A role for EC2
        Value: !Ref ProfileInstance
        Export:
            Name: !Sub ${EnvironmentName}-ProfileInstance
